version: '2.4'

services:
    audio_processor:
        container_name: audio_processor
        image: 'audio_processor:latest'
        build:
          context: .
          dockerfile: ./Dockerfile
        restart: unless-stopped
        networks:
          - proxy-redirect
        hostname: audio_processor
        volumes:
          - './config/:/app/config/'
        mem_limit: 300mb
        logging:
          driver: "json-file"
          options: 
            max-size: "10m"
            max-file: "3"
        
#### Network ####
networks:
    proxy-redirect:
        external: true
        name: proxy-redirect